### ISSUE TITLE
Use offscreen canvas

### ISSUE THREAD

**Issue by fuzhenn** [axmand/fusion.gl#38]
可以改用Offscreen Canvas API在web worker中做webgl绘制, 每次绘制完成后, 再交还给主线程

https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/

目前OffScreeen Canvas API已经在chrome和firefox中得到支持, 将来应该会有更多浏览器做支持

**Comment by axmand** [comment]
嗯，之前设计的多输出已实验过offscreen,后因浏览器支持不足的原因暂时放弃
